# Generated by Django 3.2.5 on 2021-08-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('discounts', models.TextField()),
                ('date', models.DateField()),
                ('cpf', models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='cpf')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
