FROM node:12.18.2-alpine

WORKDIR /usr/src/app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./
RUN npm cache clean --force && npm i

COPY . .

RUN npm install
RUN npm install -g @angular/cli

CMD ng serve --host 0.0.0.0