FROM node:12.18.2-alpine

WORKDIR /usr/src/app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./

COPY . .

RUN npm install -g @angular/cli && npm install

CMD ng serve --host 0.0.0.0